# Numpy


In [73]:
!pip install numpy


In [74]:
import numpy as np

## 1D Array

In [75]:


arr =np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [76]:
np.size(arr)

6

In [77]:
np.shape(arr)

(6,)

In [78]:
arr2.dtype

dtype('int32')

## 2D Array

In [79]:


arr2 =np.array([[1,4,5,6,2,3],[4,5,8,9,7,6]])
arr2

array([[1, 4, 5, 6, 2, 3],
       [4, 5, 8, 9, 7, 6]])

In [80]:
np.size(arr2)

12

In [81]:
np.shape(arr2)

(2, 6)

In [82]:
print(arr2.dtype)

int32


## 3D Array

In [83]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
print(arr3[0, 1, 2])

6


# Simple Operation


In [85]:
arr

array([1, 2, 3, 4, 5, 6])

In [86]:
arr+2

array([3, 4, 5, 6, 7, 8])

In [87]:
arr2

array([[1, 4, 5, 6, 2, 3],
       [4, 5, 8, 9, 7, 6]])

In [88]:
arr2+1

array([[ 2,  5,  6,  7,  3,  4],
       [ 5,  6,  9, 10,  8,  7]])

In [89]:
arr*3

array([ 3,  6,  9, 12, 15, 18])

In [90]:
np.sum(arr)

21

In [91]:
np.mean(arr)

3.5

In [92]:
np.max(arr)

6

In [93]:
np.min(min)

<function min>

In [94]:
np.min(arr)

1

In [95]:
np.median(arr)

3.5

In [96]:
np.std(arr)

1.707825127659933

# Indexing
    
    

In [97]:
#- Basic indexing

arr

array([1, 2, 3, 4, 5, 6])

In [98]:
arr[3]

4

In [99]:
arr[-3]

4

In [100]:
arr[-1]

6

In [101]:
arr[-1*2]

5

In [102]:
arr[1:3]

array([2, 3])

In [103]:
arr[1 ]

2

# Slicing

In [104]:
arr[:]

array([1, 2, 3, 4, 5, 6])

In [105]:
arr[1:]

array([2, 3, 4, 5, 6])

In [106]:
 arr[:1]

array([1])

Negative Slicing

In [110]:
arr[-3:-1]

array([4, 5])

In [111]:
arr[-1]

6

In [112]:
arr[-1:]

array([6])

In [113]:
arr[:-1]

array([1, 2, 3, 4, 5])

STEP

In [114]:
newarr=np.array([10,20,30,40,50,60,70,80,90])
newarr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [116]:
newarr[2:4:6]

array([30])

In [117]:
newarr[1:5:2]

array([20, 40])

Slicing 2-D Arrays

In [118]:
arr2

array([[1, 4, 5, 6, 2, 3],
       [4, 5, 8, 9, 7, 6]])

In [119]:
arr2[1, 1:4]

array([5, 8, 9])

In [120]:
arr2[0:2, 2]

array([5, 8])

# Matrix Operation

In [123]:
x=np.array([1,1,1,1])
y=np.array([2,2,2,2])
res=np.dot(x,y)
res

8

# Numpy Random

In [124]:
#Generate Random Number

np.random.rand()

0.8523586705710313

In [133]:
z=np.random.randint(100)
z

74

In [135]:
#Generate Random Float
a=np.random.rand()
a

0.13352783200857998

In [143]:
#shuffle array ele randomly

p=np.array([100,200,300,400,500])
np.random.shuffle(p)
print(p)

[200 400 100 300 500]


In [1]:
def myfun():
    print("Vrushali")

myfun()

Vrushali


In [9]:
my_set = {1, 2, 3, 4, 5, 5}
my_set.add(6)  # Adds 6 to the set
my_set.add(40)
print(my_set)  # Output: {1, 2, 3, 4, 5, 6} (duplicates are not stored)


{1, 2, 3, 4, 5, 6, 40}
